
import 'swiper/css';
import 'aos/dist/aos.css';
import 'swiper/css/navigation';
import "../../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Nunito } from "next/font/google";

const nunito = Nunito({
  weight: "500",
  subsets: ["cyrillic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        {children}
      </body>
    </html>
  );
}
